config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  # root "articles#index"
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_posts_counter

  def most_recent_comments
    comments.order('created_at DESC').limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def most_recent_posts
    posts.order('created_at DESC').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index; end

  def show; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="w-full block">
    <%= render partial: "partials/userCard", locals: { user: @user } %>

    <div class="border-2 w-full my-5 px-3 pt-3 pb-5">
        <h2 class="text-xl font-medium">Bio</h2>
        <p class="mt-5">
            <%= @user.bio %>
        </p>
    </div>

    <div class="mt-7">
        <ul>
            <% @user.most_recent_posts.each_with_index do |post,index| %>
                <li class="my-5">
                    <%= render partial: "partials/postCard", locals:{ post: post, index:index } %>
                </li>
            <% end %>
        </ul>
    </div>

    <div class="flex justify-center">
        <button class=" border-2 px-4 ">
            <%= link_to "See all posts", user_posts_path(@user) %>
        </button>
    </div>
</div>